ixnetwork_open_traffic_generator/ixnetworkapi.py
tests/utils/common.py

We're now returning list of result.Port and result.Flow instead of flow dict and port dict.

Fixed https://github.com/open-traffic-generator/ixnetwork/issues/71

---

tests/udp/test_raw_traffic_with_fixed_udp_ports.py
tests/udp/test_udp_fixed_ports.py

Adding udp related test with ref #93

adding udp tests

---

tests/udp/test_udp_header_with_fixed_length_fixed_checksum.py
tests/utils/common.py

adding udp test-2

---

README.md

lgtm alerts badge.  lgtm now runs on each PR.

added lgtm badge.

---

tests/udp/test_udp_header_with_counter.py
tests/udp/test_udp_header_with_fixed.py
tests/udp/test_udp_header_with_list.py
tests/udp/test_udp_header_with_random.py
tests/udp_e2e/test_udp_fixed_ports.py
tests/udp_e2e/test_udp_header_with_counter.py
tests/udp_e2e/test_udp_header_with_fixed_length_fixed_checksum.py
tests/udp_e2e/test_udp_header_with_list.py
tests/utils/common.py

adding udp tests for #95  & #98

add udp tests

---

tests/tcp/test_tcp_control_flags.py
tests/tcp/test_tcp_header_with_counter.py
tests/tcp/test_tcp_header_with_fixed.py
tests/tcp/test_tcp_header_with_list.py
tests/tcp/test_tcp_header_with_random.py
tests/tcp_e2e/test_counter_tcp_ports.py
tests/tcp_e2e/test_list_tcp_ports.py
tests/tcp_e2e/test_random_tcp_ports.py

add tcp tests

---

.github/workflows/publish.yml
README.md
tests/conftest.py
tests/ethernet/test_counter_mac_addr.py
tests/ethernet/test_fixed_mac_addrs.py
tests/ethernet/test_list_mac_addrs.py
tests/ipv4/test_counter_ip_addrs.py
tests/ipv4/test_fixed_ip_addrs.py
tests/ipv4/test_list_ip_addrs.py
tests/pytest.ini
tests/tcp/test_counter_tcp_ports_e2e.py
tests/tcp/test_list_tcp_ports_e2e.py
tests/tcp/test_random_tcp_ports_e2e.py
tests/tcp/test_tcp_control_flags.py
tests/tcp/test_tcp_header_with_counter.py
tests/tcp/test_tcp_header_with_fixed.py
tests/tcp/test_tcp_header_with_list.py
tests/tcp/test_tcp_header_with_random.py
tests/traffic/test_tcp_flow_capture.py
tests/udp/test_udp_fixed_ports_e2e.py
tests/udp/test_udp_header_with_counter.py
tests/udp/test_udp_header_with_counter_e2e.py
tests/udp/test_udp_header_with_fixed.py
tests/udp/test_udp_header_with_fixed_length_checksum_e2e.py
tests/udp/test_udp_header_with_list.py
tests/udp/test_udp_header_with_list_e2e.py
tests/udp/test_udp_header_with_random.py

Fixes:
- https://github.com/open-traffic-generator/ixnetwork/issues/126
- https://github.com/open-traffic-generator/ixnetwork/issues/118

Utils refactor

---

tests/ipv4/test_counter_ipv4_fields.py
tests/ipv4/test_fixed_ipv4_fields.py
tests/ipv4/test_list_ipv4_fields.py
tests/utils/common.py
tests/vlan/test_counter_vlan_fields.py
tests/vlan/test_fixed_vlan_fields.py
tests/vlan/test_list_vlan_fields.py
tests/vlan/test_random_vlan_fields.py
tests/vlan/test_vlan_double_tag.py

vlan test cases and ipv4 fields testcases
with restpy validation

vlan and ipv4 tests

---

ixnetwork_open_traffic_generator/ixnetworkapi.py
ixnetwork_open_traffic_generator/vport.py

This pull request for issue #122

port_names argument support for result.PortRequest

---

ixnetwork_open_traffic_generator/customfield.py
ixnetwork_open_traffic_generator/ixnetworkapi.py
ixnetwork_open_traffic_generator/trafficitem.py
ixnetwork_open_traffic_generator/vport.py
tests/conftest.py

Duplicate entry causes incorrect stack/field entry.

Remove duplicate dscp phb entry

---

ixnetwork_open_traffic_generator/trafficitem.py

fix for https://github.com/open-traffic-generator/ixnetwork/issues/145

Traffic stop state is not working

---

ixnetwork_open_traffic_generator/trafficitem.py

fix for https://github.com/open-traffic-generator/ixnetwork/issues/146

traffic pause state is not working

---

ixnetwork_open_traffic_generator/customfield.py
ixnetwork_open_traffic_generator/vport.py
tests/test_flow_ipv4.py

This pull request will address these issues:
https://github.com/open-traffic-generator/ixnetwork/issues/162
https://github.com/open-traffic-generator/ixnetwork/issues/163
https://github.com/open-traffic-generator/ixnetwork/issues/164

Multiple bug fixes

---

ixnetwork_open_traffic_generator/ixnetworkapi.py

restport is wrongly assigned with password variable.
https://github.com/open-traffic-generator/ixnetwork/issues/184

connect call bug fix

---

ixnetwork_open_traffic_generator/ixnetworkapi.py
tests/pfc/test_pfc_pause_counter_pattern.py
tests/pfc/test_pfc_pause_fixed_pattern.py
tests/pfc/test_pfc_unpause.py

pfc testcases unit test and upause scripts

pfc_unit_and_unpause

---

tests/statistics/test_port_and_flow_stats.py
tests/statistics/test_port_and_flow_stats_e2e.py
tests/utils/common.py

adding stats testcases for #123,#124,#140,#141

adding stats testcases

---

tests/pfc/test_global_unpause_e2e.py
tests/pfc/test_pfc_unpause_e2e.py

1. Added test script fro global un puase.
2. appended e2e to pfc_unpause test file name and test name

un-pause global pause

---

ixnetwork_open_traffic_generator/ixnetworkapi.py
ixnetwork_open_traffic_generator/trafficitem.py
ixnetwork_open_traffic_generator/vport.py

This will address #155 #160 and #161

Novus 10G and 100G

---

ixnetwork_open_traffic_generator/trafficitem.py

Header retained in the flow from previous run

---

ixnetwork_open_traffic_generator/vport.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/206

Name conflict

---

ixnetwork_open_traffic_generator/ngpf.py

Enhancement of counter pattern for Device Config.
#215

Enhancement of counter pattern

---

tests/ipv4/test_ip_priority_field.py

Unit Test Cases for Ip DSCP and TOS.

Unit Test Cases for Ip DSCP and TOS

---

ixnetwork_open_traffic_generator/vport.py

This should address this fix https://github.com/open-traffic-generator/ixnetwork/issues/203

AutoNegotiation is not applied on 10G Novus

---

ixnetwork_open_traffic_generator/vport.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/209

Support Capture overwrite argument

---

tests/traffic/test_ip_device_and_flow.py

Test Case for device config, counter pattern and flows

Test Case for device config, counter pattern and flows

---

.github/workflows/publish.yml
tests/pytest.ini

adding l1_manual marker

---

ixnetwork_open_traffic_generator/trafficitem.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/168

Traffic is not resuming on the paused flow

---

tests/capture/test_capture_filter_settings.py
tests/capture/test_capture_overwrite.py

adding capture tests

---

ixnetwork_open_traffic_generator/vport.py

Address https://github.com/open-traffic-generator/ixnetwork/issues/209#issuecomment-759371245

Disable captureTriggerEnable for captureContinuousMode

---

ixnetwork_open_traffic_generator/trafficitem.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/235
Please take a look and let me know if this will address customer use case as well as do not regress anything

Flow framesize is being ignored #235

---

tests/capture/test_capture_overwrite.py

removing skip as #209 fixed

---

ixnetwork_open_traffic_generator/ixnetworkapi.py

This fix will return RequestDetail object for set_state. So the code looks like:
config_state = control.ConfigState(config=config, state='set')
result = api.set_state(control.State(config_state))
print(result.errors)
print(result.warnings)
Please review and let me know if this will fulfill the requirement.

Support RequestDetail

---

snappi_ixnetwork/ixnetworkapi.py
snappi_ixnetwork/trafficitem.py
snappi_ixnetwork/vport.py
tests/traffic/test_stats_filter.py
tests/utils/common.py

metrics fix

---

snappi_ixnetwork/trafficitem.py

fix for other traffic units

---

snappi_ixnetwork/trafficitem.py

fix_flow_size_increment

---

tests/ipv4/test_ip_priority_field.py
tests/test_clear_config.py
tests/test_devices.py
tests/test_flow_duration.py
tests/traffic/test_stats_filter.py
tests/utils/common.py

snappi unit test map

---

snappi_ixnetwork/ngpf.py

This will address https://github.com/open-traffic-generator/ixnetwork/issues/265

BGP As_path and Community Support

---

snappi_ixnetwork/ixnetworkapi.py

This will address 
https://github.com/open-traffic-generator/ixnetwork/issues/272

stop all when run standalone script

---

setup.py
snappi_ixnetwork/customfield.py
tests/conftest.py
tests/ethernet/test_counter_mac_addr.py
tests/ipv4/test_ip_priority_field.py
tests/test_bgp_speaker.py
tests/test_demonstrate_test_structure.py
tests/test_flow_duration.py
tests/test_get_ingress_results.py
tests/test_phb_ecn.py
tests/test_ports.py
tests/test_short_duration_flow_results.py
tests/test_staggered_flow_start.py

Snappi ixnetwork UT cases

---

snappi_ixnetwork/ixnetworkapi.py
snappi_ixnetwork/protocolmetrics.py
tests/bgp/test_bgpv4_stats.py
tests/settings.json

BGP Metrics Updated with review comments resolution

BGP Metrics Updated with review comments

---

snappi_ixnetwork/ixnetworkapi.py
snappi_ixnetwork/resourcegroup.py
snappi_ixnetwork/vport.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/283

UHD speed support

---

snappi_ixnetwork/ngpf.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/286

Fix BGP RR Remove Issue

---

snappi_ixnetwork/resourcegroup.py
tests/conftest.py
tests/layer1/test_layer1_uhd.py
tests/test_flow_rate.py
tests/test_flow_size.py
tests/traffic/test_tcp_flow_capture.py

UHD test case and minor fix

---

ixnetwork_open_traffic_generator/trafficitem.py

regex fix for flow names.
issue is with flow names, special characters needs to be parsed from the flow names.
ex:
"Test Flow 0 -> 1 **(**prio 4**)**" --> brackets need to be replaced with escape sequence

regex fix for flow names

---

ixnetwork_open_traffic_generator/trafficitem.py
tests/config_files/test.json
tests/test_flownames.py

flow names regex fix in flow stats

flow names regex fix in flow stats

---

snappi_ixnetwork/ixnetworkapi.py
snappi_ixnetwork/trafficitem.py

https://github.com/open-traffic-generator/ixnetwork/issues/302
https://github.com/open-traffic-generator/ixnetwork/issues/303
https://github.com/open-traffic-generator/ixnetwork/issues/304

minor fixes

---

snappi_ixnetwork/ngpf.py

fix for metric and origin

---

snappi_ixnetwork/capture.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/313

Expose start capture

---

tests/bgp/test_bgp_attributes.py

Adding tests against issue #270

adding bgp attributes unit test

---

.vscode/settings.json
snappi_ixnetwork/customfield.py
tests/pfc/test_global_pause_e2e.py
tests/pfc/test_global_unpause_e2e.py
tests/pfc/test_pfc_pause_e2e.py
tests/pfc/test_pfc_unpause_e2e.py
tests/traffic/test_ip_device_and_flow.py

ethernet pause header fix
https://github.com/open-traffic-generator/ixnetwork/issues/314

ethernet pause header fix

---

tests/vlan/test_counter_vlan_fields.py
tests/vlan/test_fixed_vlan_fields.py
tests/vlan/test_list_vlan_fields.py
tests/vlan/test_vlan_double_tag.py

deleted the existing vlan_ut branch.

vlan_ut_cases

---

snappi_ixnetwork/ixnetworkapi.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/280

ixn version check

---

snappi_ixnetwork/capture.py
snappi_ixnetwork/ixnetworkapi.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/336

Seen capture issue

---

snappi_ixnetwork/capture.py
snappi_ixnetwork/ixnetworkapi.py
snappi_ixnetwork/lag.py
snappi_ixnetwork/ngpf.py
snappi_ixnetwork/trafficitem.py
snappi_ixnetwork/vport.py
tests/bgp/test_bgpv4_stats.py
tests/bgp/test_bgpv6_routes.py

PR due to https://github.com/open-traffic-generator/ixnetwork/issues/304

Special regex char

---

snappi_ixnetwork/trafficitem.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/253

Flow metrics latency support

---

snappi_ixnetwork/resourcegroup.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/343

Different Novus 100G

---

snappi_ixnetwork/trafficitem.py

Issue https://github.com/open-traffic-generator/ixnetwork/issues/358

Add Suspend to check pause traffic

---

.github/workflows/publish.yml
setup.py
snappi_ixnetwork/trafficitem.py
tests/pfc/test_global_pause_e2e.py
tests/pfc/test_global_unpause_e2e.py
tests/pfc/test_pfc_pause_e2e.py
tests/pfc/test_pfc_unpause_e2e.py
tests/test_flow_duration.py
tests/test_lag.py

This should address https://github.com/open-traffic-generator/ixnetwork/issues/354

Choice delay gap

---

snappi_ixnetwork/exceptions.py
snappi_ixnetwork/trafficitem.py
tests/errors/test_errors.py
tests/metrics/test_diff_latency_mode.py

tracebacks

---

tests/convergence/test_convergence.py

adding bgp metrics to UT

---

snappi_ixnetwork/ngpf.py
snappi_ixnetwork/trafficitem.py
tests/test_issue_7.py

fix for issue reported https://github.com/open-traffic-generator/snappi-convergence/issues/7

fix for issue_7

---

tests/capture/test_capture_filter_settings.py
tests/capture/test_capture_overwrite.py
tests/test_flow_duration.py
tests/test_flow_rate.py
tests/test_flow_size.py
tests/test_lag.py
tests/test_ports.py

update tests with port location preemption

update tests with port location preemption

---

snappi_ixnetwork/snappi_api.py

adding api key to headers

---

setup.py
snappi_ixnetwork/customfield.py
snappi_ixnetwork/exceptions.py
snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/timer.py
snappi_ixnetwork/trafficitem.py
tests/ipv4/test_ip_priority_field.py
tests/pfc/test_global_pause_unit.py
tests/traffic/test_api_perf_new.py
tests/traffic/test_traffic_device.py
tests/traffic/test_traffic_json.py
tests/traffic/test_traffic_perf.py
tests/utils/common.py

closed other PR as it has merge conflicts, this PR has all comments addressed raised by Alakendu

Traffic performance enhancement with json

---

setup.py
snappi_ixnetwork/protocolmetrics.py
tests/bgp/test_bgpv4_stats.py
tests/bgp/test_bgpv6_routes.py
tests/convergence/test_convergence.py
tests/traffic/test_device_bgp_ep.py

updating concrete implementation and tests to align with snappi version == 0.4.26

updating protocol metrics

---

do.py
setup.py
snappi_ixnetwork/events.py
snappi_ixnetwork/serdes.py

This should address https://github.com/open-traffic-generator/snappi-ixnetwork/issues/421

Add pytest coverage

---

snappi_ixnetwork/lag.py

This should address https://github.com/open-traffic-generator/snappi-ixnetwork/issues/428

Add translate in LAG property

---

do.py
snappi_ixnetwork/ngpf.py
snappi_ixnetwork/snappi_convergence_api.py
tests/bgp/test_bgpv4_stats.py
tests/traffic/test_device_bgp_ep.py

This will address https://github.com/open-traffic-generator/snappi-ixnetwork/issues/434

handle Compacting IPv6

---

requirements.txt
tests/test_compact.py
tests/traffic/test_device_bgp_ep.py

update compact UT to support ipv6

update compact UT to support ipv6

---

snappi_ixnetwork/snappi_convergence_api.py
snappi_ixnetwork/trafficitem.py

This will address these issues : 
https://github.com/open-traffic-generator/snappi-ixnetwork/issues/445
https://github.com/open-traffic-generator/snappi-ixnetwork/issues/444

Use Traffic Items instead of Flows

---

readme.md

Snappi --> snappi

---

snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/trafficitem.py
tests/test_flow_tracking_stats.py

Add flow tracking enable for flow stats to add breaking support for 0.3.x

Add flow tracking enable for flow stats

---

.github/workflows/publish.yml

Actions fix on forked PRs

---

snappi_ixnetwork/trafficitem.py
tests/ipv6/test_ipv6_fields.py

resolving ipv6 src/dst configure not working

---

snappi_ixnetwork/trafficitem.py
tests/vxlan/test_vxlan_e2e.py
tests/vxlan/test_vxlan_fields.py

adding vxlan to packet headers

adding vxlan to packet headers

---

snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/trafficitem.py
tests/metrics/test_flow_metrics.py

This should support for port and flow for this issue https://github.com/open-traffic-generator/snappi-ixnetwork/issues/467

flow metric separation

---

snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/trafficitem.py
tests/convergence/test_convergence.py
tests/test_update_flow.py

support for update flows API on ixnetwork

support for update flows API on ixnetwork

---

snappi_ixnetwork/trafficitem.py
tests/arp/test_arp_packet.py
tests/arp/test_arp_packet_e2e.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/477

Add ARP Packet

---

do.py
snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/trafficitem.py
tests/conftest.py
tests/test_flow_tracking.py
tests/test_issue_7.py

Support for flow stats in 0.7.x

Support for flow stats in 0.7.x

---

.gitignore
do.py
setup.py
snappi_ixnetwork/trafficitem.py
tests/traffic/test_traffic_json.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/486

Auto Feature fix

---

requirements.txt
setup.py
tests/ipv6/test_ipv6_next_header.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/501

Auto Feature enable for ipv6 next hop

---

.vscode/settings.json
setup.py
snappi_ixnetwork/device/ngpf.py
tests/conftest.py
tests/test_device_connection.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/503

Device chaining Implementation

---

.github/workflows/publish.yml
do.py
requirements.txt

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/495

Trigger Snappi Test CI after Snappi ixnetwork

---

snappi_ixnetwork/device/ngpf.py
tests/vxlan/test_vxlan_b2b_scale.py
tests/vxlan/test_vxlan_compact.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/514
Chain DGs are compacted and set multiplier as 4.

compact chain DG

---

snappi_ixnetwork/capture.py
tests/capture/test_capture_control.py
tests/conftest.py
tests/utils/common.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/522

Issue522: Capture is failing in tests in 9.20

---

snappi_ixnetwork/snappi_api.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/516

fetch error from name when description missing

---

snappi_ixnetwork/trafficitem.py
tests/pfc/test_global_pause_unit.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/473

Global Pause support for 9.20

---

snappi_ixnetwork/trafficitem.py
tests/udp/test_udp_header_with_fixed_length_checksum_e2e.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/535

Added custom pattern fix for field

---

snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/vport.py
tests/test_issue_microsoft.py

Fix for Wait_for_Arp in sonic-mgmt tests

---

snappi_ixnetwork/capture.py
snappi_ixnetwork/device/base.py
snappi_ixnetwork/device/bgp.py
snappi_ixnetwork/device/compactor.py
snappi_ixnetwork/device/createixnconfig.py
snappi_ixnetwork/device/interface.py
snappi_ixnetwork/device/loopbackint.py
snappi_ixnetwork/device/ngpf.py
snappi_ixnetwork/device/vxlan.py
snappi_ixnetwork/logger.py
snappi_ixnetwork/objectdb.py
snappi_ixnetwork/snappi_api.py
snappi_ixnetwork/snappi_convergence_api.py
snappi_ixnetwork/trafficitem.py
snappi_ixnetwork/vport.py
tests/conftest.py
tests/test_logger.py

resolves https://github.com/open-traffic-generator/snappi-ixnetwork/issues/533

Logger support

---

setup.py
snappi_ixnetwork/device/ngpf.py
snappi_ixnetwork/lag.py
snappi_ixnetwork/snappi_api.py
tests/test_device_connection.py
tests/test_issue_microsoft.py
tests/test_lag.py

LAG changes to align with models 0.8.1

---

setup.py
snappi_ixnetwork/device/base.py
snappi_ixnetwork/device/interface.py
tests/vxlan/test_manual_gateway_mac.py

support for manual gateway mac

---

.github/workflows/publish.yml
do.py
requirements.txt

This modification allows formatting the report and sending mail.
Log file : 
https://github.com/open-traffic-generator/snappi-ixnetwork/actions/runs/13009162607/job/36282763266
sample mail:
sample report:
https://otg.dev/snappi-ixnetwork/

Format result

---

do.py
setup.py
snappi_ixnetwork/trafficitem.py
tests/utils/common.py

Newly added fields in flow metrics:
tx_l1_rate_bps
rx_l1_rate_bps
tx_rate_bytes
rx_rate_byte
tx_rate_bps
rx_rate_bps
tx_rate_kbps
rx_rate_kbps
tx_rate_mbps
rx_rate_mbps
@arkajyoti-cloud @alakendu

Flow Stats support for additional fields

---

snappi_ixnetwork/trafficitem.py
tests/macsec/test_macsec_mka_multiple_devices.py

MACsec PR contains:
1. Throw error with message when MACsec raw traffic is configured as it is not supported now
2. Test case for checking how MACsec/ MKA scales in IxNetwork when multiple devices are added

MACsec raw traffic error handling and MACsec/ MKA scale test

---

.github/workflows/publish.yml
do.py

1. Bug fix: Fix test coverage logic
2. Added Pass rate
3. Island failure if UT or sanity pass rate fall under threshold
4. Mail report on each submission only in main.

CI Bug Fix
